language: python
python:
  - "3.6"

cache: pip

services:
  - docker

env:
  global:
    - IMG=tdmproject/tdm-ingestion
#  matrix:
#    - BACKEND=sync
#    - BACKEND=async


install:
  - pip install -e .[confluent]
  - pip install kafka

script:
  - cd tests
  - python -m unittest
  - cd -
  - make tests

deploy:
  - provider: script
    script: bash .travis/push.sh
    on:
      repo: tdm-project/tdm-ingestion
      branch: master
